const url = 'https://my.api.mockaroo.com/jobs.json?key=7d344dd0';

const getJobs = () => {
  // return newData;
  return axios.get(url);
};

const newData = {
  data: [
    {
      id: 1,
      company: 'Meeveo',
      logo: 'http://dummyimage.com/150x150.png/cc0000/ffffff',
      isNew: false,
      isFeatured: false,
      position: 'Librarian',
      role: 'Backend',
      level: 'Midweight',
      location: 'USA Only',
      languages: ['Python', 'C#', 'CSS'],
      tools: ['RoR', 'Vue', 'Svelte', 'React'],
      contract: 'Full Time',
      postedAt: '01/21/2023',
    },
    {
      id: 2,
      company: 'Zoomzone',
      logo: 'http://dummyimage.com/150x150.png/cc0000/ffffff',
      isNew: false,
      isFeatured: false,
      position: 'Operator',
      role: 'Fullstack',
      level: 'Senior',
      location: 'UK Only',
      languages: ['C#', 'JavaScript'],
      tools: ['Angular', 'Django', 'Sass', 'RoR'],
      contract: 'Full Time',
      postedAt: '07/15/2022',
    },
    {
      id: 3,
      company: 'Mymm',
      logo: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
      isNew: false,
      isFeatured: true,
      position: 'Recruiting Manager',
      role: 'Frontend',
      level: 'Midweight',
      location: 'Worldwide',
      languages: ['HTML'],
      tools: ['React', 'Tailwind'],
      contract: 'Contract',
      postedAt: '04/16/2023',
    },
    {
      id: 4,
      company: 'Shuffledrive',
      logo: 'http://dummyimage.com/150x150.png/cc0000/ffffff',
      isNew: false,
      isFeatured: true,
      position: 'Help Desk Technician',
      role: 'Frontend',
      level: 'Senior',
      location: 'Worldwide',
      languages: ['C#', 'Python'],
      tools: ['Vue', 'Tailwind', 'Angular', 'RoR'],
      contract: 'Full Time',
      postedAt: '07/26/2022',
    },
    {
      id: 5,
      company: 'Bubblebox',
      logo: 'http://dummyimage.com/150x150.png/cc0000/ffffff',
      isNew: true,
      isFeatured: true,
      position: 'Editor',
      role: 'Fullstack',
      level: 'Senior',
      location: 'Worldwide',
      languages: ['HTML'],
      tools: ['Django', 'ASP.NET', 'Vue'],
      contract: 'Full Time',
      postedAt: '04/29/2023',
    },
    {
      id: 6,
      company: 'Eadel',
      logo: 'http://dummyimage.com/150x150.png/dddddd/000000',
      isNew: true,
      isFeatured: false,
      position: 'Account Representative II',
      role: 'Frontend',
      level: 'Senior',
      location: 'UK Only',
      languages: ['Python'],
      tools: ['Svelte', 'ASP.NET'],
      contract: 'Full Time',
      postedAt: '03/28/2023',
    },
    {
      id: 7,
      company: 'Voonyx',
      logo: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
      isNew: true,
      isFeatured: true,
      position: 'Dental Hygienist',
      role: 'Frontend',
      level: 'Senior',
      location: 'UK Only',
      languages: ['Python', 'C#'],
      tools: ['Angular'],
      contract: 'Contract',
      postedAt: '07/09/2023',
    },
    {
      id: 8,
      company: 'Photolist',
      logo: 'http://dummyimage.com/150x150.png/dddddd/000000',
      isNew: true,
      isFeatured: false,
      position: 'Internal Auditor',
      role: 'Frontend',
      level: 'Senior',
      location: 'USA Only',
      languages: ['Python', 'CSS', 'HTML'],
      tools: ['Django', 'Vue', 'ASP.NET', 'Angular'],
      contract: 'Contract',
      postedAt: '07/01/2023',
    },
    {
      id: 9,
      company: 'Blogtag',
      logo: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
      isNew: true,
      isFeatured: true,
      position: 'Budget/Accounting Analyst III',
      role: 'Backend',
      level: 'Junior',
      location: 'Remote',
      languages: ['Python', 'HTML', 'CSS'],
      tools: ['Tailwind'],
      contract: 'Full Time',
      postedAt: '01/28/2023',
    },
    {
      id: 10,
      company: 'Edgeclub',
      logo: 'http://dummyimage.com/150x150.png/cc0000/ffffff',
      isNew: true,
      isFeatured: true,
      position: 'Professor',
      role: 'Frontend',
      level: 'Midweight',
      location: 'Worldwide',
      languages: ['JavaScript'],
      tools: ['Vue', 'ASP.NET', 'Tailwind'],
      contract: 'Part Time',
      postedAt: '02/15/2023',
    },
    {
      id: 11,
      company: 'Riffpath',
      logo: 'http://dummyimage.com/150x150.png/cc0000/ffffff',
      isNew: true,
      isFeatured: false,
      position: 'Safety Technician III',
      role: 'Fullstack',
      level: 'Midweight',
      location: 'USA Only',
      languages: ['Python', 'JavaScript', 'C#'],
      tools: ['Django'],
      contract: 'Part Time',
      postedAt: '01/20/2023',
    },
    {
      id: 12,
      company: 'Bluezoom',
      logo: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
      isNew: true,
      isFeatured: true,
      position: 'General Manager',
      role: 'Fullstack',
      level: 'Senior',
      location: 'Remote',
      languages: ['Python', 'HTML'],
      tools: ['React'],
      contract: 'Full Time',
      postedAt: '05/24/2023',
    },
    {
      id: 13,
      company: 'Talane',
      logo: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
      isNew: false,
      isFeatured: true,
      position: 'Assistant Manager',
      role: 'Frontend',
      level: 'Senior',
      location: 'USA Only',
      languages: ['HTML', 'CSS', 'C#'],
      tools: ['Django', 'RoR'],
      contract: 'Part Time',
      postedAt: '09/05/2022',
    },
    {
      id: 14,
      company: 'Gabtune',
      logo: 'http://dummyimage.com/150x150.png/5fa2dd/ffffff',
      isNew: false,
      isFeatured: false,
      position: 'Assistant Professor',
      role: 'Frontend',
      level: 'Midweight',
      location: 'USA Only',
      languages: ['Python', 'C#'],
      tools: ['ASP.NET', 'React', 'Angular', 'Svelte'],
      contract: 'Part Time',
      postedAt: '05/31/2023',
    },
    {
      id: 15,
      company: 'Mudo',
      logo: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
      isNew: true,
      isFeatured: true,
      position: 'Legal Assistant',
      role: 'Backend',
      level: 'Junior',
      location: 'UK Only',
      languages: ['CSS', 'Python'],
      tools: ['Svelte', 'Vue', 'Tailwind'],
      contract: 'Contract',
      postedAt: '11/30/2022',
    },
    {
      id: 16,
      company: 'Kwilith',
      logo: 'http://dummyimage.com/150x150.png/5fa2dd/ffffff',
      isNew: true,
      isFeatured: false,
      position: 'Recruiter',
      role: 'Backend',
      level: 'Midweight',
      location: 'Remote',
      languages: ['C#', 'HTML', 'JavaScript'],
      tools: ['React'],
      contract: 'Contract',
      postedAt: '11/28/2022',
    },
    {
      id: 17,
      company: 'Photolist',
      logo: 'http://dummyimage.com/150x150.png/cc0000/ffffff',
      isNew: false,
      isFeatured: true,
      position: 'Junior Executive',
      role: 'Fullstack',
      level: 'Junior',
      location: 'USA Only',
      languages: ['CSS'],
      tools: ['Angular', 'Vue', 'React', 'ASP.NET'],
      contract: 'Full Time',
      postedAt: '10/03/2022',
    },
    {
      id: 18,
      company: 'Tagfeed',
      logo: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
      isNew: false,
      isFeatured: true,
      position: 'Account Representative II',
      role: 'Frontend',
      level: 'Midweight',
      location: 'USA Only',
      languages: ['CSS', 'HTML', 'C#'],
      tools: ['Tailwind', 'Django'],
      contract: 'Full Time',
      postedAt: '03/05/2023',
    },
    {
      id: 19,
      company: 'Skiptube',
      logo: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
      isNew: true,
      isFeatured: true,
      position: 'Engineer II',
      role: 'Fullstack',
      level: 'Junior',
      location: 'Remote',
      languages: ['C#'],
      tools: ['React'],
      contract: 'Contract',
      postedAt: '08/02/2023',
    },
    {
      id: 20,
      company: 'Realpoint',
      logo: 'http://dummyimage.com/150x150.png/dddddd/000000',
      isNew: true,
      isFeatured: true,
      position: 'Operator',
      role: 'Backend',
      level: 'Senior',
      location: 'USA Only',
      languages: ['JavaScript'],
      tools: ['Django'],
      contract: 'Part Time',
      postedAt: '07/07/2023',
    },
  ],
};
